In [1]:
import numpy as np

In [2]:
# 1.矩阵求和
Z = np.arange(9).reshape(3,3)
print('Z is \n',Z)
print(Z.sum(axis = 0))# 传统按行/列求和函数
C = np.einsum('ij->j',Z)# 按
print(C)

Z is 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]
[ 9 12 15]


In [3]:
# 2.3Darray求和
Z = np.arange(27).reshape((3,3,3))
print('Z is \n',Z)
print(Z.sum(axis=0))# 3D数组按一维求和
C = np.einsum('ijk->ij',Z)
print(C)

Z is 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[27 30 33]
 [36 39 42]
 [45 48 51]]
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]


In [4]:
# 3.更高维度 求和
Z = np.arange(81).reshape((3,3,3,3))
print('Z is \n',Z)
# print(Z.sum(axis=0))# 3D数组按一维求和
print(np.einsum('ijkl->...l',Z))# 可以用...代替更高维度的表达

Z is 
 [[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]
   [24 25 26]]]


 [[[27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]]

  [[45 46 47]
   [48 49 50]
   [51 52 53]]]


 [[[54 55 56]
   [57 58 59]
   [60 61 62]]

  [[63 64 65]
   [66 67 68]
   [69 70 71]]

  [[72 73 74]
   [75 76 77]
   [78 79 80]]]]
[1053 1080 1107]


In [5]:
# 4.两个矩阵相乘（点乘）
A = np.ones((3,3))
B = np.arange(9).reshape(3,3)
print(A)
print(B)
print(np.dot(A,B)) # 传统方法，矩阵点乘
C = np.einsum('ij,jk->ik',A,B)
print(C)   

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9. 12. 15.]
 [ 9. 12. 15.]
 [ 9. 12. 15.]]
[[ 9. 12. 15.]
 [ 9. 12. 15.]
 [ 9. 12. 15.]]


In [6]:
# 5.张量乘法
A = np.ones((3,3))
B = np.arange(9).reshape(3,3)
print(np.tensordot(A,B,([0, 1], [0, 1])))

36.0


In [7]:
# 5.1张量：张量就是高维的数据
# 一维张量：矢量 [1,2,3,4]^T
# 二维张量：矩阵 [[1,2,3],[4,5,6],[7,8,9]]
# 三维张量：矩阵数组 P
# 四维张量 的矢量(?) [P1,P2,P3]^T
C = [[[1], [2]],
     [[3], [4]],
     [[4], [2]]] 
           
c = np.array(C)
print(c)
c.shape

[[[1]
  [2]]

 [[3]
  [4]]

 [[4]
  [2]]]


(3, 2, 1)

In [8]:
# 6.计算矩阵的迹——主对角线上各个元素的总和
A = np.arange(9).reshape(3,3)
print(A)
# 三种方法
print(np.einsum('ii', A)) # implicit mode
print(np.einsum(A, [0,0]))# einsum(op0, sublist0, op1, sublist1, ..., [sublistout])方式 implicit mode
print(np.trace(A))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
12
12
12


In [9]:
# 7.计算矩阵的转置
print(A)
print(np.einsum('ij->ji',A))
print(A.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [10]:
# 8. 矩阵的对角元素
print(np.diag(A))
print(np.einsum('ii->i',A))
print(np.einsum(A,[0,0],[0]))

[0 4 8]
[0 4 8]
[0 4 8]


In [23]:
# 9.指定维度求和
print(A)
print(np.einsum('ij->i',A))
print(np.sum(A,axis=1))
print(np.einsum(A, [0,1], [0]))
# einsum(op0, sublist0, op1, sublist1, ..., [sublistout])方式 explicit mode

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 3 12 21]
[ 3 12 21]
[ 3 12 21]


In [28]:
# 10.计算矩阵转置
print(A)
print(np.transpose(A, axes=[1,0]))
print(np.einsum('ij->ji',A))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [36]:
# 11.向量内积
a = np.array([1,2,3,4,5])
print(a)
print(np.einsum('i,i',a,a)) # 向量内积
print(np.inner(a,a))

[1 2 3 4 5]
55
55


In [45]:
# 12.矩阵与向量的乘积
j = np.array([1,2,3])
print(A)
print(j)
print(np.einsum('ij,j->i',A,j)) # A*j
print(np.einsum(A, [0,1], j, [1]))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 2 3]
[ 8 26 44]
[ 8 26 44]


In [53]:
# 13.广播机制
print(A)
print(np.einsum('...,...',A,3))
print(np.einsum(',ij',3,A))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


[[4400. 4730.]
 [4532. 4874.]
 [4664. 5018.]
 [4796. 5162.]
 [4928. 5306.]]


NameError: name 'b' is not defined