In [1]:
# 1.导入numpy包
import numpy as np

In [2]:
# 2.打印numpy版本和设置
print(np.__version__)
print(np.show_config)

1.18.5
<function show at 0x000001FAEDDCECA0>


In [4]:
# 3.创建一个空的10个长度的向量
zeroArr = np.zeros(10)
print(zeroArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# 4.如何找到任何一个array的长度
print('ZeroArr\'s size is',zeroArr.size)
# ItemSize返回字节长度
print('ZeroArr\'s itemsize is',zeroArr.itemsize)

ZeroArr's size is 10
ZeroArr's itemsize is 8


In [6]:
# 5.如何在命令行里面找到numpy的函数文档
# 传入函数参数
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [7]:
# 6.创建一个长度为10的空的向量但是第5个值为1
zeroArr2 = np.zeros(10)
zeroArr2[4]=1
zeroArr2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
# 7.创建一个由10-49的数字构成的向量
arr1 = np.arange(10,50)

In [9]:
# 8.翻转一个向量
# 使用切片功能，第一个：为[)区间的数据，第二个:后为步长
arr1[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [10]:
# 9.创建一个3*3的矩阵，值为0-8
arr2 = np.arange(9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
# 10.从向量[1,2,0,0,4,0]中找到非0元素的索引
arr3 = [1,2,0,0,4,0]
np.nonzero(arr3)

(array([0, 1, 4], dtype=int64),)

In [12]:
# 11.创建一个3*3的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# 12.创建一个3*3*3的随机数矩阵
np.random.random((3,3,3))

array([[[0.38643877, 0.55191467, 0.57320164],
        [0.71770481, 0.21320487, 0.64638186],
        [0.37735844, 0.83914291, 0.61570276]],

       [[0.18919567, 0.13121087, 0.45287793],
        [0.48946465, 0.60592924, 0.45428991],
        [0.26106437, 0.62707453, 0.53242757]],

       [[0.65874109, 0.7437497 , 0.52467982],
        [0.21751081, 0.95876976, 0.87713826],
        [0.38176439, 0.52674937, 0.17132982]]])

In [14]:
# 13.创建一个10*10的随机矩阵并找到他们的最小和最大值
arr4 = np.random.random((10,10))
print('arr4 is:\n',arr4)
print('arr4\'s min is',np.min(arr4))
print('arr4\'s max is',np.max(arr4))

arr4 is:
 [[0.43331849 0.12723117 0.0442345  0.53054868 0.54055774 0.15806529
  0.77727247 0.70945836 0.14886052 0.4100046 ]
 [0.97460091 0.44721222 0.19710072 0.30864943 0.70973255 0.31650193
  0.89219494 0.67418036 0.55413258 0.93525672]
 [0.50713042 0.80934558 0.02527833 0.36645368 0.44932258 0.13831178
  0.76666867 0.51059484 0.53299124 0.24718414]
 [0.3967133  0.70024227 0.88038902 0.56332556 0.17561872 0.89687477
  0.68941898 0.17209373 0.27539626 0.58508631]
 [0.29406209 0.31169375 0.34525503 0.92852817 0.21914908 0.69996136
  0.97490877 0.81279406 0.81817753 0.60212421]
 [0.13152528 0.22801151 0.12511416 0.23639309 0.58434112 0.33795794
  0.75484864 0.80489821 0.9497258  0.78598819]
 [0.13140328 0.23805307 0.19096603 0.31802285 0.46272745 0.54733044
  0.94171767 0.61574534 0.75323355 0.47502519]
 [0.91019854 0.61762003 0.1288725  0.0817648  0.34452686 0.96006438
  0.56086413 0.20377208 0.79708483 0.38558834]
 [0.00679297 0.31829742 0.67759736 0.30703553 0.05957333 0.08110242
  

In [15]:
# 14.创建一个长度为30的随机向量并且找到平均值
arr5 = np.random.random(30)
print('arr5 is \n',arr5)
print('arr5\'s mean is',np.mean(arr5))

arr5 is 
 [0.48959879 0.01158138 0.5936598  0.04541165 0.29321194 0.84407144
 0.77246198 0.97573114 0.83157837 0.67522956 0.14742273 0.91630098
 0.9865316  0.18033049 0.79934889 0.10338969 0.47551176 0.49662644
 0.2815447  0.80388113 0.04714206 0.75524864 0.38261937 0.83834087
 0.27442207 0.07231609 0.73008793 0.63677678 0.64814176 0.48930651]
arr5's mean is 0.5199275521110563


In [16]:
# 15.创建一个二维数组，边界为1，其余为0
arr6=np.ones((10,10))
arr6[1:-1,1:-1]=0
arr6

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
# 16.如何添加一个边界由0包围的数组
# 用pad函数
arr7 = np.ones((5,5))
arr7 = np.pad(arr7,pad_width=2,mode='constant',constant_values=0)
arr7


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
# 17.下面的表达式执行结果是什么
# Tips:Nan不是一个number，不能参与很多运算
0 * np.nan # nan
np.nan == np.nan # False
np.inf > np.nan # False
np.nan - np.nan # Nan
np.nan in set([np.nan]) # True
0.3 == 3 * 0.1 # False

False

In [19]:
# 18.创建一个5*5的矩阵,1,2,3,4为对角线下方元素
# 用np.diag建立对角线矩阵，k参数控制偏移量
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [20]:
# 19.建立一个8*8的矩阵用棋盘型图案填充
# numpy切片:第一个：前后为起始、截至的index，第二个:后面为步长（间隔）
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
# 20.考虑一个(6,7,8)形状的数组，第100的元素的(x,y,z)index是什么？
# unravel_index()获得第n个元素在某个shape的ndarray下的x,y,z index
np.unravel_index(99,(6,7,8))

(1, 5, 3)

In [22]:
# 21.使用平铺功能获得8*8的棋盘式矩阵
# np.info(np.tile)
# tile 函数，对ndarray按排列进行重复
# tile(a,b) a为ndarray，b为平铺的一、二、三、......、N维平铺数量
print(np.array([[0,1],[1,0]]))
np.tile(np.array([[0,1],[1,0]]),(4,4))

[[0 1]
 [1 0]]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [23]:
# 22.标准化一个5*5的随机矩阵
arr9 = np.random.random((5,5))
arr9 = (arr9-np.mean(arr9))/(np.std(arr9))
print(arr9)

[[-0.20825435  1.40477982 -1.65469778 -0.31828578  1.56813003]
 [-1.33096804 -0.95133459 -0.25720591  1.18070701 -0.47725693]
 [ 1.28333326  0.80823702  0.30560065 -0.51765055 -0.06961653]
 [-1.5746643  -1.53906287 -0.36406482 -0.95801169  1.16659522]
 [ 0.57467438  1.03300662  1.25589933 -0.60125536  0.24136615]]


In [24]:
# 23.建立一个数据类型，把RGBA颜色用4个无符号字节描述
# np.dtype 数据类型对象是用来描述与数组对应的内存区域如何使用
# numpy.dtype(object, align, copy)
# np.info(np.dtype)
color = np.dtype([('r',np.ubyte,1),('g',np.ubyte,1),('b',np.ubyte,1),('a',np.ubyte,1)])


<ipython-input-24-08819e0d107a>:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([('r',np.ubyte,1),('g',np.ubyte,1),('b',np.ubyte,1),('a',np.ubyte,1)])


In [25]:
# 24.用一个5*3的矩阵乘以3*2的矩阵，作矩阵乘法
# np.dot()矩阵乘法运算函数
np.dot(np.ones((5,3)),np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [26]:
# 25.给出一个一维数组，取3到8之间所有元素的值的负数
arr10 = np.array([3,6,4,5,7,9,1,2,8])
# 数组对象[条件判断]表达式
arr10[(3<arr10)&(arr10<8)]*=-1
print(arr10)

[ 3 -6 -4 -5 -7  9  1  2  8]


In [27]:
# 26.下列脚本的输出是？
# print(sum(range(5),-1))
# from numpy import *
# print(sum(range(5),-1))
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [28]:
# 27.一个整型向量Z，哪个表达式是合法的
Z = np.arange(3)
Z**Z #合法
2 << Z >> 2 #合法
Z <- Z # 合法
1j*Z # 合法
Z/1/1 # 合法
Z<Z>Z #不合法
# The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
# 28.下列表达式的结果是什么
np.array(0) / np.array(0) #Nan
np.array(0) // np.array(0) #0
np.array([np.nan]).astype(int).astype(float)# 有结果

In [ ]:
# 29.如何把一个float型数组取整
Z = np.random.uniform(-10,+10,10)
np.around(Z) # around函数

In [ ]:
# 30.如何找到两个矩阵中的共同值
X = np.abs(np.around(np.random.uniform(-10,+10,10)))
Y = np.abs(np.around(np.random.uniform(-10,+10,10)))
Z = np.abs(np.around(np.random.uniform(-10,+10,10)))
print(X,Y,Z)
np.intersect1d(X,Y)

In [29]:
# 31.如何忽略warnings
np.seterr(all='ignore')# 不提示
Z = np.ones(1) / 0
_ = np.seterr(**defaults)# 回到默认


NameError: name 'defaults' is not defined

In [30]:
# 32.下面的表达式是True吗
np.sqrt(-1) == np.emath.sqrt(-1)
# np.emath对象是对虚数进行操作

False

In [31]:
# 33.如何获取昨天、今天和明天的日期
today = np.datetime64('today')
yesterday = np.datetime64('today')-np.timedelta64(1)
tomorrow = np.datetime64('today')+np.timedelta64(1)
print(today,yesterday,tomorrow)

2020-10-12 2020-10-11 2020-10-13


In [32]:
# 34.如何获得某个时间段内的所有时间
# 通过arange()函数，传入时间参数和dtype格式
during = np.arange('2020-07','2020-10',dtype='datetime64[D]')
print(during)

['2020-07-01' '2020-07-02' '2020-07-03' '2020-07-04' '2020-07-05'
 '2020-07-06' '2020-07-07' '2020-07-08' '2020-07-09' '2020-07-10'
 '2020-07-11' '2020-07-12' '2020-07-13' '2020-07-14' '2020-07-15'
 '2020-07-16' '2020-07-17' '2020-07-18' '2020-07-19' '2020-07-20'
 '2020-07-21' '2020-07-22' '2020-07-23' '2020-07-24' '2020-07-25'
 '2020-07-26' '2020-07-27' '2020-07-28' '2020-07-29' '2020-07-30'
 '2020-07-31' '2020-08-01' '2020-08-02' '2020-08-03' '2020-08-04'
 '2020-08-05' '2020-08-06' '2020-08-07' '2020-08-08' '2020-08-09'
 '2020-08-10' '2020-08-11' '2020-08-12' '2020-08-13' '2020-08-14'
 '2020-08-15' '2020-08-16' '2020-08-17' '2020-08-18' '2020-08-19'
 '2020-08-20' '2020-08-21' '2020-08-22' '2020-08-23' '2020-08-24'
 '2020-08-25' '2020-08-26' '2020-08-27' '2020-08-28' '2020-08-29'
 '2020-08-30' '2020-08-31' '2020-09-01' '2020-09-02' '2020-09-03'
 '2020-09-04' '2020-09-05' '2020-09-06' '2020-09-07' '2020-09-08'
 '2020-09-09' '2020-09-10' '2020-09-11' '2020-09-12' '2020-09-13'
 '2020-09-

In [41]:
# 35.如何计算((A+B)*(-A/2))不通过copy
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
print(A,B,C)
# 加法
np.add(A,B,out = A)
print(A)
# 除法
np.divide(A,2,out=A)
print(A)
# 相反数
np.negative(A,out=A)
print(A)
# 翻倍的倍数
np.multiply(A,C,out=A)
print(A)

[1. 1. 1.] [2. 2. 2.] [3. 3. 3.]
[3. 3. 3.]
[1.5 1.5 1.5]
[-1.5 -1.5 -1.5]
[-4.5 -4.5 -4.5]


In [50]:
# 36.用四种不同的方法，从一个随机数构成的数组中取出随机数里面的整数位部分
Z = np.random.uniform(0,10,10)# 产生10个0-10区间内的随机数
print(Z)
print(Z-Z%1) #对1取余会得到小数点后的数
print(np.floor(Z)) #floor函数直接对数取整
print(Z.astype(int)) #astype(int)函数，进行强制类型转换
print(np.trunc(Z)) #np.trunc函数，转换类型

[9.90348548 0.72435075 4.27918681 6.1713914  0.68623456 2.32226196
 0.14024712 2.24395762 0.23078504 4.38199487]
[9. 0. 4. 6. 0. 2. 0. 2. 0. 4.]
[9. 0. 4. 6. 0. 2. 0. 2. 0. 4.]
[9 0 4 6 0 2 0 2 0 4]
[9. 0. 4. 6. 0. 2. 0. 2. 0. 4.]


In [57]:
# 37.创建一个行元素区间在0-4之间的5*5矩阵
Z = np.zeros((5,5))# 定义一个0矩阵
Z += np.arange(5)# 生成一个一维ndarray
print(Z)# 利用ndarray计算是每个行都计算的特性

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [65]:
# 38.定义一个生成函数，生成10个整数，并用它构建一个数组
def generator():
# 生成函数定义（生成器）
    for i in range(10):
        yield i#
        
print(np.fromiter(generator(),int,3))
# np.fromiter()函数，根据一个生成器iterator，返回一个dtype类型，n个个数的ndarray

    

[0 1 2]


In [87]:
# 39.生成一个长度为10的向量，值在0，1开区间
Z = np.linspace(0,1,11,endpoint=False)[1:] # linspace()函数，返回一个区间内的等差数列，设定
print(Z)
# start:返回样本数据开始点
# stop:返回样本数据结束点
# num:生成的样本数据量，默认为50
# endpoint：True则包含stop；False则不包含stop
# retstep：If True, return (samples, step), where step is the spacing between samples.(即如果为True则结果会给出数据间隔)
# dtype：输出数组类型
# axis：0(默认)或-1


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [90]:
# 40.建立一个长度为10的随机数组并排序，用sort(函数)
Z = np.random.random(10)
Z.sort()
print(Z)

[0.01290856 0.24795886 0.26136835 0.40345    0.41976022 0.46542431
 0.67922514 0.68120371 0.74230564 0.75696577]


In [92]:
# 41.如何比np.sum()函数更快的求一个小型array的和
# add.reduce
np.add.reduce(Z)# 相加

4.670570560745431

In [98]:
# 42.判断两个array是否相等
a1 = np.array([1,3,5])
a2 = np.array([1,3,5])
np.equal(a1,a2) # 用np.equal()仅能判断每个元素是否相等
np.array_equal(a1,a2) # np.array_equal()能够判断是否相等
np.allclose(a1,a2)# allclose()函数能够判断array是否相等

True

In [102]:
# 43.创建一个只读的array
a3 = np.array([1,3,5])
a3.flags.writeable = False #通过array的flag.writeable参数控制
a3[1]=0

ValueError: assignment destination is read-only

In [22]:
# 44.创建一个10行2列的随机矩阵，表示笛卡尔坐标系，将其转换为极坐标
coords = np.random.random((10,2))
print(coords)
X = coords[:,0]
Y = coords[:,1]
R = np.sqrt(X**2+Y**2)
O = np.arctan2(Y,X)
print(R,O)

[[0.20911219 0.62961865]
 [0.66928533 0.1851879 ]
 [0.65433753 0.91422411]
 [0.02131345 0.08965517]
 [0.18014335 0.34633786]
 [0.61376124 0.3779544 ]
 [0.48830132 0.77704083]
 [0.76600943 0.15733682]
 [0.4550075  0.98124231]
 [0.03598329 0.47855182]]
[0.66343617 0.69443315 1.12426124 0.09215375 0.3903864  0.72079983
 0.91773124 0.78200084 1.0816045  0.47990274] [1.25013353 0.26994135 0.94959121 1.33740174 1.09116872 0.55195649
 1.00974763 0.20258054 1.1366035  1.49574551]


In [25]:
# 45.创建一个长度为10的随机向量，并且将最大值替换为0
Z = np.random.random(10)
print(Z)
Z[np.argmax(Z)]=0
print(Z)

[0.65425711 0.55839631 0.16318146 0.33705772 0.4936048  0.08547886
 0.10858873 0.72759516 0.09804005 0.77707286]
[0.65425711 0.55839631 0.16318146 0.33705772 0.4936048  0.08547886
 0.10858873 0.72759516 0.09804005 0.        ]


In [39]:
# 46.创建一个结构化的数组，元素用x，y坐标组成，覆盖[0,1]*[0,1]的区域
Z = np.zeros((5,5),[('x',float),('y',float)])
# meshgrid函数：生成坐标矩阵,meshgrid里面两维数据，一维x，一维y，按linspace进行排列
Z['x'],Z['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [46]:
# 47.给出两个数组，构造柯西矩阵
X = np.arange(10)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)#用x-y，启用广播机制
print(C)
print(np.linalg.det(C))# 线性代数运算，求行列式的值

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333 -0.11764706 -0.10526316]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615 -0.13333333 -0.11764706]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818 -0.15384615 -0.13333333]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222 -0.18181818 -0.15384615]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429 -0.22222222 -0.18181818]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.         -0.66666667 -0.4       ]
 [ 0.13333333  0.153846

In [54]:
# 48. 打印每种numpy数量类型的最小和最大可表示值（int、float等类型的数据范围)
for dtype in [np.int0,np.int8,np.int16,np.int32,np.int64]:
    print(dtype,'min:',np.iinfo(dtype).min)
    print(dtype,'max:',np.iinfo(dtype).max)
for dtype in [np.float,np.float16,np.float32,np.float64]:
    print(dtype,'min',np.finfo(dtype).min)
    print(dtype,'max',np.finfo(dtype).max)
    print(dtype,'eps',np.finfo(dtype).eps)

<class 'numpy.int64'> min: -9223372036854775808
<class 'numpy.int64'> max: 9223372036854775807
<class 'numpy.int8'> min: -128
<class 'numpy.int8'> max: 127
<class 'numpy.int16'> min: -32768
<class 'numpy.int16'> max: 32767
<class 'numpy.int32'> min: -2147483648
<class 'numpy.int32'> max: 2147483647
<class 'numpy.int64'> min: -9223372036854775808
<class 'numpy.int64'> max: 9223372036854775807
<class 'float'> min -1.7976931348623157e+308
<class 'float'> max 1.7976931348623157e+308
<class 'float'> eps 2.220446049250313e-16
<class 'numpy.float16'> min -65500.0
<class 'numpy.float16'> max 65500.0
<class 'numpy.float16'> eps 0.000977
<class 'numpy.float32'> min -3.4028235e+38
<class 'numpy.float32'> max 3.4028235e+38
<class 'numpy.float32'> eps 1.1920929e-07
<class 'numpy.float64'> min -1.7976931348623157e+308
<class 'numpy.float64'> max 1.7976931348623157e+308
<class 'numpy.float64'> eps 2.220446049250313e-16


In [78]:
# 49.如何打印一个ndarray下的所有值，设置np.printoption()的参数
np.printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [83]:
# 50.如何找到在一个向量中给定尺度下最近的值
Z=np.arange(10)# 给出一个数组
Y=np.random.uniform(0,10)# 给出一个值
index = (np.abs(Z-Y)).argmin() # 用数组与数运算计算距离array，用argmin定位到距离最小index
print(Z[index])# 输出index对应的value

5


In [89]:
# 51.创建一个结构化的一维数组表示位置position:x,y和颜色color:r,g,b
# 定义dtype,dtype是一个列表，里面每一项是一个元组，第一项是name，第二项是一个列表，内容是定义属性的元组
Z = np.zeros(10,[('positon',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-89-62aa52e03b44>:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10,[('positon',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])


In [109]:
# 52.定义一个随机向量，10*2，表示坐标，找到点到点之间的距离
Z = np.random.random((3,2))*10
X,Y = np.atleast_2d(Z[:,0],Z[:,1]) # 将输入的数组转换为至少两维，此处把坐标的行列均转换为两维数据
print(Z,'\n')
print(X,'\n')
print(Y,'\n')

D = np.sqrt((X-X.T)**2+(Y-Y.T)**2)# 利用ndarray的
print(D)


[[1.43496526 8.1579524 ]
 [8.56791629 5.06008577]
 [7.43384123 1.66938646]] 

[[1.43496526 8.56791629 7.43384123]] 

[[8.1579524  5.06008577 1.66938646]] 

[[0.         7.77661675 8.83674154]
 [7.77661675 0.         3.57532769]
 [8.83674154 3.57532769 0.        ]]


In [117]:
# 53. 如何把一个32位的float数组转换为integer的在本地
# tips:使用view和[:]
Z = (np.random.random(10)).astype(np.float32)*10
print(Z,'\n')
Y = Z.view(np.int32)# view在本地进行内存区域的切割操作，无需开辟新的内存空间
Y[:]=Z
print(Y)


[5.022795  1.3192581 9.882374  7.326775  1.7056857 1.9440364 7.834335
 8.764394  1.0810813 9.742402 ] 

[5 1 9 7 1 1 7 8 1 9]


In [119]:
# 54.如何读取下面的文件
# 1, 2, 3, 4, 5
# 6,  ,  , 7, 8
#  ,  , 9,10,11
from io import StringIO # 导入string io模块

s = StringIO('''
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
 ''')
Z = np.genfromtxt(s,delimiter=',',dtype=np.int) # 从txt中获取ndarray，传入字符串IO，输入分隔符，类型
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [126]:
# 55.numpy数组的枚举是什么？
Z=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(Z):
    print(index,value)# index为行列的index元组，value为值
print('\n')
for index in np.ndindex(Z.shape):
    print(index,Z[index])
    
# ndenumerate和ndindex返回不同的结果，具有不同的用法

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [133]:
# 56.生成通用的二维高斯分布数组（正态分布）
X,Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))# 生成两个-1,1之间均匀分布的mesh网格数据
D=np.sqrt(X*X+Y*Y) # 进行平方和开方处理
sigma,mu =1.0,0.0 # 初始化sigma和miu
G =np.exp(-((D-mu)**2/(2.0*sigma**2))) # 形成正态分布公式
print(G) # 输出

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [139]:
# 57.如何在2D数组中随机放置p个元素？采用put函数
n = 10
p = 5
Z = np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace=False),1)
# put函数
# 第一个参数为ndarray
# 第二个参数为choice函数，传入range(n^2)个index，给定替换的个数p，以及是否可以替代
# 第三个参数为替代的数据
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [161]:
# 58.减去矩阵每一行的均值
Z = (np.random.random((5,3))*10).astype(np.int)
print(Z,'\n')
# ndarray.mean(axis,keepdims) 传入按行还是按列求平均，是否保持原有维度
M = Z.mean(axis=1, keepdims=True) 
print(M,'\n')
print(Z-M)

[[9 2 4]
 [6 3 3]
 [9 4 2]
 [5 7 6]
 [6 3 0]] 

[[5.]
 [4.]
 [5.]
 [6.]
 [3.]] 

[[ 4. -3. -1.]
 [ 2. -1. -1.]
 [ 4. -1. -3.]
 [-1.  1.  0.]
 [ 3.  0. -3.]]


In [178]:
# 59.如何通过第n列排列一个数组
Z = np.random.randint(0,10,(3,3))
print(Z,'\n')
print(Z[Z[:,1].argsort()]) # Z[:]按行或列排序.argsort()返回一组排序号的index顺序

[[6 9 2]
 [2 3 4]
 [5 7 8]] 

[[2 3 4]
 [5 7 8]
 [6 9 2]]


In [192]:
# 60.给出一个二维数组，如何告知有空的列
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())
print(Z.any(axis=0))
print((Z.any(axis=0)).any())
# 表达式：非（Z中的每个列，判断是否为0，返回一个array）对一维array判断是否有False

[[0 1 0 2 2 0 1 1 0 0]
 [0 1 1 1 0 0 2 2 0 2]
 [1 1 2 2 2 1 2 1 2 1]]
False
[ True  True  True  True  True  True  True  True  True  True]
True


In [213]:
# 61. 找到array中距离给定value最近的值
Z = np.random.uniform(0,10,(3,3))
p = 5
print(Z)
# print(Z[np.argmin(np.abs(Z-p))])
# 一维数组可以直接使用索引，高维应该使用flat函数遍历
print(Z.flat[np.argmin(np.abs(Z-p))])

[[4.45856377 2.89447008 4.17126521]
 [5.5354448  9.6882285  7.75146524]
 [7.64631089 2.04619791 6.26537492]]
5.53544480172847


In [225]:
# 62.两个(1,3) and (3,1)的array，如何使用一个迭代器计算他们的和
X1 = np.random.randint(0,5,(1,3))
X2 = np.random.randint(0,5,(3,1))
print(X1,'\n\n',X2)
it = np.nditer([X1,X2,None])
for x,y,z in it:
    z[...]=x+y
print(it.operands[2])



[[3 0 4]] 

 [[2]
 [3]
 [2]]
[[5 2 6]
 [6 3 7]
 [5 2 6]]


array([[5, 2, 6],
       [6, 3, 7],
       [5, 2, 6]])

In [14]:
# 63.创建一个k数组类，有一个name属性
class NamedClass(np.ndarray):
    def __new__(cls,array,name = 'noname',info = 'what'):
        obj = np.asarray(array).view(cls)
        obj.name = name
        obj.infomation = info
        return obj
    def __array_finalize__(self,obj):
        if obj is None:return
        self.info = getattr(obj,'name','what')
        
Z = NamedClass(np.arange(10),'range_10','hhh')
print(Z.name)
print(Z.info)

range_10
what


In [52]:
# 64a.考虑一个给定的向量，如何增加1到每个由另一个向量标注的index元素上（注意重复索引）
Z = (np.zeros(10)).astype('int32')
index = np.array([1,3,3,3,3,3,5,8,9])
print(Z, index)
np.add.at(Z,index,1) # add.at()函数，在某个向量的某些位置增加，index为一维有效
print(Z)

[0 0 0 0 0 0 0 0 0 0] [1 3 3 3 3 3 5 8 9]
[0 1 0 5 0 1 0 0 1 1]


In [49]:
# 64b.考虑一个给定的向量，如何增加1到每个由另一个向量标注的index元素上（注意重复索引）
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print(Z,I)
# bincount函数，返回非空整型数组中的每个元素的索引值出现的次数
# minlength为bin函数返回值最少的长度
print(np.bincount(I, minlength=len(Z)) )
Z += np.bincount(I, minlength=len(Z)) 
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [5 9 5 3 3 3 0 0 0 7 2 8 4 2 3 3 5 5 6 3]
[3 0 2 6 1 4 1 1 1 1]
[4. 1. 3. 7. 2. 5. 2. 2. 2. 2.]


In [68]:
# 65.如何基于一个index列表累积向量X的元素到数组
# np.bincount(A,B):把B中的value作为index，从1中挑选元素，累积到新的array的相应index位置
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,100]
F = np.bincount(I,X)
print(F)

[0. 1. 0. 6. 5. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 6.]


In [73]:
# 66.考虑（dtype = ubyte）的（w，h，3）图像，计算唯一出现的颜色的数量
# np.unique(ndarray)：计算ndarray中唯一元素的数量
w,h=16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
print(I)
print(F)
n = len(np.unique(F))
print(n)
print(np.unique(I))

[[[1 0 0]
  [0 1 0]
  [1 0 0]
  [1 1 0]
  [1 0 1]
  [1 0 0]
  [1 0 1]
  [1 0 1]
  [0 1 1]
  [1 1 0]
  [0 0 0]
  [1 1 0]
  [1 1 1]
  [1 0 1]
  [0 0 0]
  [1 1 1]]

 [[1 1 0]
  [0 1 0]
  [1 1 1]
  [1 0 0]
  [0 0 0]
  [0 0 0]
  [1 0 1]
  [1 1 0]
  [1 1 1]
  [0 0 1]
  [1 1 0]
  [0 0 1]
  [0 1 1]
  [0 0 0]
  [1 0 1]
  [0 1 1]]

 [[0 0 1]
  [1 0 0]
  [1 0 1]
  [1 0 1]
  [0 0 0]
  [1 0 0]
  [0 0 0]
  [1 0 1]
  [1 1 1]
  [1 1 1]
  [0 0 0]
  [1 1 0]
  [1 1 1]
  [1 0 1]
  [0 1 1]
  [0 1 1]]

 [[1 0 0]
  [0 1 0]
  [1 0 0]
  [0 0 1]
  [1 0 1]
  [0 1 0]
  [1 1 1]
  [1 0 0]
  [0 0 0]
  [1 1 0]
  [1 0 0]
  [1 0 0]
  [0 0 1]
  [0 0 1]
  [1 1 0]
  [1 0 1]]

 [[0 1 1]
  [1 0 0]
  [0 0 1]
  [1 1 1]
  [0 1 1]
  [1 0 0]
  [1 1 1]
  [1 0 1]
  [0 0 1]
  [1 1 1]
  [1 0 0]
  [1 0 1]
  [0 1 0]
  [0 1 0]
  [1 0 1]
  [0 1 1]]

 [[0 1 0]
  [0 0 0]
  [1 0 0]
  [0 1 1]
  [0 1 1]
  [0 0 1]
  [1 1 1]
  [0 1 0]
  [0 0 0]
  [0 0 1]
  [0 0 0]
  [0 1 0]
  [0 1 0]
  [1 0 0]
  [0 0 1]
  [1 0 0]]

 [[1 0 0]
  [0 1 0]
  [0 0 0

In [78]:
# 67.一个四维array，如何一次性获取后两个轴的sum
A = np.random.randint(0,10,(3,4,3,4))
print(A)
sum = A.sum(axis = (-2,-1))
print(sum)

[[[[9 5 8 9]
   [2 5 5 6]
   [7 3 0 6]]

  [[8 7 9 3]
   [6 2 2 3]
   [1 0 9 4]]

  [[8 5 4 9]
   [5 0 0 8]
   [9 9 2 8]]

  [[2 3 9 6]
   [8 7 9 3]
   [8 7 4 0]]]


 [[[7 3 6 7]
   [0 4 4 3]
   [3 4 4 9]]

  [[9 6 2 0]
   [6 3 0 7]
   [2 2 5 6]]

  [[4 5 9 6]
   [3 3 5 9]
   [5 6 0 0]]

  [[8 3 1 5]
   [0 6 0 6]
   [1 9 4 5]]]


 [[[6 9 9 6]
   [1 6 0 2]
   [4 1 7 9]]

  [[4 9 3 7]
   [5 4 9 7]
   [9 1 9 0]]

  [[6 5 9 3]
   [1 7 4 9]
   [2 3 7 6]]

  [[2 4 5 9]
   [4 7 5 3]
   [8 2 2 5]]]]
[[65 54 67 66]
 [54 48 55 48]
 [60 67 62 56]]


In [88]:
# 68.一个一维向量D，如何使用描述子集索引的相同大小的向量S计算D子集的均值
D = np.random.uniform(0,1,100)
print(D)
S = np.random.randint(0,10,100)
print(S)
D_sums = np.bincount(S,weights = D) # 指定weights参数，对应index的value索引为weights[index'VALUE]的权重
D_counts =np.bincount(S)
D_means = D_sums/D_counts
print(D_means)

[0.63977644 0.2323187  0.88921129 0.07521363 0.98022096 0.08512115
 0.74453894 0.06298775 0.24200959 0.9773675  0.8703807  0.98968829
 0.01309644 0.97968731 0.36809975 0.41478278 0.15152223 0.32785015
 0.22125913 0.60443774 0.27109468 0.71238127 0.53941215 0.06547751
 0.91537042 0.07922311 0.61768875 0.65621369 0.91121891 0.26682725
 0.39287964 0.73787976 0.50631551 0.48664161 0.8530906  0.74710297
 0.46864941 0.79460981 0.29085039 0.87206907 0.41666441 0.18951093
 0.44434384 0.79684474 0.07103324 0.70891668 0.47746263 0.6497526
 0.59725988 0.07351635 0.83892189 0.40459129 0.65248512 0.34457178
 0.21560256 0.31317832 0.87730816 0.64551354 0.66837437 0.39721312
 0.09339042 0.26852998 0.4320418  0.74841653 0.10704873 0.0249851
 0.52487199 0.67213714 0.53609681 0.79297843 0.67272554 0.51220842
 0.16391017 0.17918743 0.19734338 0.78077599 0.42445278 0.06026545
 0.08972847 0.1171091  0.61998009 0.33763736 0.41231912 0.35940008
 0.46838353 0.57064733 0.01591029 0.982689   0.36308833 0.460959

In [105]:
# 69.如何获得点积的对角线——三种方法
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(np.dot(A,B))
#慢的操作
print(np.diag(np.dot(A,B)))
#快点的操作:A*B的转置并按列求和
# A*B.T
print(np.sum(A*B.T,axis = 1))
#更快的操作：使用einsum函数，对i,j,k控制
print(np.einsum('ij,ji->i',A,B))

[[0.8126526  1.08310313 0.80727823 1.46526872 1.30861716]
 [0.66092457 0.85554201 0.98055598 1.24210479 1.25202785]
 [0.9076759  1.0478919  1.09915283 1.12754925 1.38812731]
 [1.21916728 1.24305569 1.25290707 1.92624639 1.91363931]
 [0.35952846 0.95144564 0.89889044 0.94066492 0.97506045]]
[0.8126526  0.85554201 1.09915283 1.92624639 0.97506045]
[0.8126526  0.85554201 1.09915283 1.92624639 0.97506045]
[0.8126526  0.85554201 1.09915283 1.92624639 0.97506045]


In [116]:
# 70.数组[1,2,3,4,5]，如何建立一个新矢量，每个值之间插入n个连续的零
# tips：利用切片的步长属性
Z = np.array([1,2,3,4,5])
n = 2
Z0 = np.zeros(len(Z) + (len(Z)-1)*(n))
Z0[::n+1]=Z
print(Z0)

[1. 0. 0. 2. 0. 0. 3. 0. 0. 4. 0. 0. 5.]


In [126]:
# 71.一个(5,5,3)维度的数组，如何乘以一个尺寸为(5,5)的数组
# Tips:用切片增加ndarray维度
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# print(B[:,:,None])# 给B增加一个维度
print(A*B[:,:,None])

[[[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]]
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [133]:
# 72. 如何交换一个数组的两行
Z = np.arange(9).reshape((3,3))
Z[[2,0]] = Z[[0,2]]# 用arrray[[]] = array[[]]方法
print(Z)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [161]:
# 73。考虑一组描述三个三角形（带有共享顶点）的10个三元组，
# 找到组成所有三角形的一组唯一线段

faces = np.random.randint(0,100,(10,3))
# print(faces)
# np.roll()：array的滚动函数
# array.repeat():array复制的倍数,axis控制行/列
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 36) ( 1, 48) ( 2, 14) ( 2, 94) ( 4, 21) ( 4, 24) ( 5, 43) ( 5, 81)
 ( 5, 87) ( 5, 94) ( 6, 18) ( 6, 57) (14, 94) (18, 57) (21, 24) (24, 53)
 (24, 82) (26, 37) (26, 73) (36, 48) (37, 73) (41, 43) (41, 83) (43, 83)
 (43, 87) (53, 82) (54, 85) (54, 95) (81, 94) (85, 95)]


In [192]:
# 74. 给出一个array C，是个bincount，如何生成一个array A，令np.bincount(A) == C?
C = np.bincount([1,1,2,3,4,4,6])
print('C:',C)
D = np.arange(len(C))
print(D)
A = np.repeat(np.arange(len(C)),C) #利用np.repeat的特性，按Carray次数重复
print(A)

C: [0 2 1 1 2 0 1]
[0 1 2 3 4 5 6]
[1 1 2 3 4 4 6]


In [205]:
# 75.如何使用数组上的滑动窗口计算平均值 hint: np.cumsum(累加)
def moving_average(a,n=3):#设定输入array和窗口
    ret = np.cumsum(a,dtype=float)
    print(ret)
    ret[n:]= ret[n:]-ret[:-n]
    print(ret)
    return ret[n-1:]/n
Z = np.arange(20)
print(Z)
print(moving_average(Z))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0.   1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91.
 105. 120. 136. 153. 171. 190.]
[ 0.  1.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42. 45. 48.
 51. 54.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [4]:
# 76.一维数组Z，建立一个二维数组，第一行是Z0，Z1，Z2，每一行都移动1，最后一行是-3,-2,-1
from numpy.lib import stride_tricks

def rolling(a,window):
    shape = (a.size-window+1,window)# 根据size和window构造shape
    print(shape)
    strides = (a.itemsize,a.itemsize)# 构造间隔
    print(strides)
    return stride_tricks.as_strided(a,shape=shape,strides=strides)# 进行切块
Z = rolling(np.arange(10),3)
print(Z)

(8, 3)
(4, 4)
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [225]:
# 77.如何取反布尔值，或更改原位浮动符号
# hint: np.logical_not, np.negative
A1 = np.random.randint(0,3,10)
A2 = np.random.randint(0,3,10)
B = A1==A2
print(B)
np.logical_not(B,out=B)# 用logical_not逻辑操作函数
print(B)

A3 = np.random.uniform(-1.0,1.0,100)
print(A3)
np.negative(A3,out = A3)# np.negative()函数，对float型数组进行取反

[False  True False False False False  True False False  True]
[ True False  True  True  True  True False  True  True False]
[-0.65673705 -0.409875    0.03104188  0.44553659  0.18506469 -0.51159897
  0.16425454  0.35983556 -0.25520893 -0.69278122  0.24223598 -0.16286717
  0.85003607  0.91840139  0.29110249 -0.56166474  0.20726547 -0.54470857
 -0.31454101  0.09997587 -0.64404263  0.85462594 -0.94511693  0.17107354
 -0.92267785 -0.17124063  0.75261935  0.1614224   0.1625776   0.97456074
  0.73935788  0.9779731   0.45948775 -0.66322442 -0.40472883  0.36663582
 -0.19266401  0.83278049  0.72948212 -0.99253567  0.51851567 -0.2810945
  0.41042918 -0.22199113  0.23128642 -0.61434727 -0.74846218 -0.97049363
  0.45377255  0.68844126 -0.00696725  0.54585575 -0.32956466 -0.23488445
 -0.41197012  0.30361848 -0.62366344  0.68412602 -0.22078788 -0.2091005
  0.202314   -0.74233298 -0.39476534  0.29984004 -0.73421545 -0.87577056
  0.42341499 -0.21609475 -0.02988981 -0.8962376   0.73714434 -0.96766378
  

array([ 0.65673705,  0.409875  , -0.03104188, -0.44553659, -0.18506469,
        0.51159897, -0.16425454, -0.35983556,  0.25520893,  0.69278122,
       -0.24223598,  0.16286717, -0.85003607, -0.91840139, -0.29110249,
        0.56166474, -0.20726547,  0.54470857,  0.31454101, -0.09997587,
        0.64404263, -0.85462594,  0.94511693, -0.17107354,  0.92267785,
        0.17124063, -0.75261935, -0.1614224 , -0.1625776 , -0.97456074,
       -0.73935788, -0.9779731 , -0.45948775,  0.66322442,  0.40472883,
       -0.36663582,  0.19266401, -0.83278049, -0.72948212,  0.99253567,
       -0.51851567,  0.2810945 , -0.41042918,  0.22199113, -0.23128642,
        0.61434727,  0.74846218,  0.97049363, -0.45377255, -0.68844126,
        0.00696725, -0.54585575,  0.32956466,  0.23488445,  0.41197012,
       -0.30361848,  0.62366344, -0.68412602,  0.22078788,  0.2091005 ,
       -0.202314  ,  0.74233298,  0.39476534, -0.29984004,  0.73421545,
        0.87577056, -0.42341499,  0.21609475,  0.02988981,  0.89

In [247]:
# 78.考虑b表示线（2d）的2组点P0，P1，以及一个点p如何计算从p到每条线i的距离
# （P0 [i]，P1 [i]）
def getDistance(P0,P1,p):
    T = P1 - P0 # 计算y1-y0,x1-x0
    L = (T**2).sum(axis=1)  # (y1-y0)**2,(x1-x0)**2
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L # 计算中间过程
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
    
    
    
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(1,2))

getDistance(P0,P1,p)

array([ 0.27509062,  1.82529796,  7.73953832,  1.72316101, 14.7962652 ,
        2.475234  , 10.05218557,  7.50467679,  0.55386511,  9.56059623])

In [249]:
# 79. 考虑描述线（2d）的2组点P0，P1和一组点P，
# 如何计算从每个点j（P [j]）到每个线i（P0 [i]，P1 [i]）的距离
# Tips:基于上一个问题的距离函数
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
P = np.random.uniform(-10, 10, (10,2))
print(np.array(getDistance(P1,P0,P) for p_i in p))

<generator object <genexpr> at 0x000001FAF2260A50>


In [250]:
# 80. 考虑一个任意数组
# 编写一个函数来提取具有固定形状并以给定元素为中心的子部分（必要时使用填充值填充）
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[1 2 6 9 1 5 7 5 1 8]
 [9 4 5 9 2 8 9 5 7 1]
 [5 8 2 4 2 5 9 6 4 8]
 [6 3 9 3 5 9 5 8 8 6]
 [9 8 0 5 0 2 4 3 6 9]
 [4 4 9 7 2 0 0 8 2 5]
 [0 8 4 2 2 5 9 3 3 3]
 [7 9 3 4 2 5 2 3 4 8]
 [5 9 7 1 9 9 5 2 8 0]
 [1 7 6 7 0 9 0 1 5 8]]
[[0 0 0 0 0]
 [0 1 2 6 9]
 [0 9 4 5 9]
 [0 5 8 2 4]
 [0 6 3 9 3]]


<ipython-input-250-094f609395a2>:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [26]:
# 81. 一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]，如何生成四个元素一个分组的二维数组
# [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]
from numpy.lib import stride_tricks
Z = np.arange(1,15,dtype=np.uint32)
print(Z)
# 用分组属性进行分组(重点在于shape和strides的设置)
# shape = (11,4)
strides = Z.itemsize*np.array([1,1])
print(strides)
D = stride_tricks.as_strided(Z,shape=shape,strides=strides)
print(R)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[4 4]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [30]:
# 82。计算一个矩阵的rank，利用线性代数工具求奇异值分解
Z = np.random.uniform(0,1,(10,10))
print(Z)
U,S,V = np.linalg.svd(Z) # svd奇异值分解
rank = sum(S>1e-10)
print(rank)

[[0.07880289 0.13384135 0.32738019 0.3348074  0.45891494 0.60183477
  0.15899197 0.96539416 0.76109885 0.99223445]
 [0.35155533 0.05989117 0.68576742 0.25992388 0.30228417 0.03442989
  0.73012719 0.24241207 0.68864123 0.48993287]
 [0.18012596 0.81806607 0.16022492 0.61078128 0.02925722 0.20672255
  0.27707397 0.66404462 0.71258882 0.20568806]
 [0.95514688 0.52183841 0.90418586 0.3802347  0.9437758  0.44374086
  0.50983835 0.89082529 0.43048962 0.85663892]
 [0.91400159 0.87646266 0.6372387  0.33095686 0.70100071 0.65437175
  0.75110038 0.22066595 0.11060494 0.67073519]
 [0.0544487  0.02666778 0.99523458 0.86942343 0.66713326 0.832946
  0.11701647 0.03513045 0.04943543 0.4180428 ]
 [0.9658868  0.97397332 0.98878863 0.12604506 0.76049793 0.33160563
  0.76886605 0.9916096  0.45879839 0.87298478]
 [0.18860659 0.6783195  0.55830951 0.70715822 0.65536036 0.38353985
  0.01631561 0.03018549 0.24950553 0.90330019]
 [0.22762432 0.87056384 0.79842136 0.34093652 0.14210953 0.86664866
  0.76210855 0

In [41]:
# 83.如何在一个array里面找到出现次数最频繁的值
# 通过bincount函数求得每个数字的出现频率，通过argmax求得这个value的index
Z = np.random.randint(0,4,10)
print(Z)
print(np.bincount(Z).argmax())


[2 3 3 1 1 2 3 3 2 0]
3


In [51]:
# 84.从一个10维随机矩阵中提取所有连续的3*3块
# stride_tricks,进行窗口移动提取
Z = np.random.randint(0,10,(10,10))
print(Z)
shape = (8,8,3,3)
strides = Z.itemsize*np.array([10,1,10,1])# 窗口的步长表示是核心
# print(Z.strides+Z.strides)
D = stride_tricks.as_strided(Z,shape=shape,strides=strides)
print(D)

[[0 5 3 0 4 7 2 7 5 7]
 [3 4 6 0 4 4 6 7 0 8]
 [6 8 1 3 5 3 6 9 5 5]
 [7 1 2 6 0 3 4 6 9 7]
 [2 4 4 1 9 9 4 4 1 3]
 [9 4 9 4 4 0 5 0 6 1]
 [7 8 2 3 8 3 6 2 9 2]
 [8 1 7 4 4 5 3 2 2 1]
 [1 7 9 7 4 2 3 0 8 9]
 [8 5 9 0 6 7 0 0 4 1]]
[[[[0 5 3]
   [3 4 6]
   [6 8 1]]

  [[5 3 0]
   [4 6 0]
   [8 1 3]]

  [[3 0 4]
   [6 0 4]
   [1 3 5]]

  [[0 4 7]
   [0 4 4]
   [3 5 3]]

  [[4 7 2]
   [4 4 6]
   [5 3 6]]

  [[7 2 7]
   [4 6 7]
   [3 6 9]]

  [[2 7 5]
   [6 7 0]
   [6 9 5]]

  [[7 5 7]
   [7 0 8]
   [9 5 5]]]


 [[[3 4 6]
   [6 8 1]
   [7 1 2]]

  [[4 6 0]
   [8 1 3]
   [1 2 6]]

  [[6 0 4]
   [1 3 5]
   [2 6 0]]

  [[0 4 4]
   [3 5 3]
   [6 0 3]]

  [[4 4 6]
   [5 3 6]
   [0 3 4]]

  [[4 6 7]
   [3 6 9]
   [3 4 6]]

  [[6 7 0]
   [6 9 5]
   [4 6 9]]

  [[7 0 8]
   [9 5 5]
   [6 9 7]]]


 [[[6 8 1]
   [7 1 2]
   [2 4 4]]

  [[8 1 3]
   [1 2 6]
   [4 4 1]]

  [[1 3 5]
   [2 6 0]
   [4 1 9]]

  [[3 5 3]
   [6 0 3]
   [1 9 9]]

  [[5 3 6]
   [0 3 4]
   [9 9 4]]

  [[3 6 9]
   [3 4 6]
   [9 4 

In [54]:
# 85. 建立一个二维的子数组类如Z[i,j] == Z[j,i]
# 生成随机的对称矩阵
# Tips:仅适用于二维数组和使用索引设置值
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
print(S)
S[2,3] = 42
print(S)

[[ 3 17  9  7  3]
 [17  7  9  5  6]
 [ 9  9  3 10  3]
 [ 7  5 10  3  5]
 [ 3  6  3  5  5]]
[[ 3 17  9  7  3]
 [17  7  9  5  6]
 [ 9  9  3 42  3]
 [ 7  5 42  3  5]
 [ 3  6  3  5  5]]


In [56]:
# 86.考虑一组形状为（n，n）的p个矩阵和一组形状为（n，1）的p个向量。 
# 如何一次计算p个矩阵乘积的总和？ （结果的形状为（n，1））
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
print(M,V)
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])# tensordot函数
print(S)

[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 ...

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]] [[[1.]
  [

In [3]:
# 87.考虑一个16*16的数组，如何获得4*4的块的和
# Author: Robert Kern

Z = np.ones((16,16))
k = 4
# np.add.reduceat:将多个块聚合
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [4]:
# 88.如何实现一个人生游戏
# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
# 89. 如何获得数组里面前n个最大的元素
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow：慢的方法，利用argsort()，获得最大的前几个index
print (Z[np.argsort(Z)[-n:]])

# Fast：快的方法，使用argpartation进行快速排列。
# 将大的元素移至右侧，小的元素移至左侧，返回index
print (Z[np.argpartition(-Z,n)[:n]])


SyntaxError: invalid character in identifier (<ipython-input-6-f860f8d7e7d8>, line 10)

In [7]:
# 90. 给定任意数量的向量，构建笛卡尔乘积（每一项的每种组合）
def cartesian(arrays): # 定义计算笛卡尔积函数
    arrays = [np.asarray(a) for a in arrays] #构造array
    shape = (len(x) for x in arrays)# 塑造shape

    ix = np.indices(shape, dtype=int) # 返回一个代表网格中所有序号的矩阵
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [8]:
# 91.如何从常规数组创建记录数组？

# 记录数组可以通过对象.属性来访问元素
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [9]:
# 92.考虑一个大向量Z，使用3种不同的方法将Z计算为3的幂
x = np.random.rand(int(5e7))

%timeit np.power(x,3) # 速度最慢
%timeit x*x*x # 速度适中
%timeit np.einsum('i,i,i->i',x,x,x) # einsum速度最快

1.73 s ± 23.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
287 ms ± 2.58 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
187 ms ± 3.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [19]:
# 93. 考虑形状为（8,3）和（2,2）的两个数组A和B。 
# 无论B中元素的顺序如何，如何查找包含B每行元素的A行？
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A)
print('\n')
print(B)
print('\n')
C = (A[..., np.newaxis, np.newaxis] == B)
print(C)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)


[[2 3 3]
 [0 0 0]
 [4 3 4]
 [0 3 4]
 [1 4 0]
 [2 1 4]
 [4 2 0]
 [3 3 1]]


[[3 4]
 [3 1]]


[[[[False False]
   [False False]]

  [[ True False]
   [ True False]]

  [[ True False]
   [ True False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False  True]
   [False False]]

  [[ True False]
   [ True False]]

  [[False  True]
   [False False]]]


 [[[False False]
   [False False]]

  [[ True False]
   [ True False]]

  [[False  True]
   [False False]]]


 [[[False False]
   [False  True]]

  [[False  True]
   [False False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False False]]

  [[False False]
   [False  True]]

  [[False  True]
   [False False]]]


 [[[False  True]
   [False False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[ True False]
   [ True False]]

  [[ True False]
   [ True False]]

  [[False False]
   [False  True]]]]
[0 2 3 4 5 7]


In [31]:
# 94.考虑10x3矩阵，请提取值不相等的行（例如[2,2,3]）
Z = np.random.randint(0,2,(10,3))
print(Z)
# 所有dtypes数组的解决方案（包括字符串数组和记录数组）
E = np.all(Z[:,1:]==Z[:,:-1],axis=1) # 进行条件和逻辑判断
print(E)
U = Z[~E]
print(U)

# 仅用于处理数值型数组，适用于Z中任意数量的列
U = Z[Z.max(axis=1) != Z.min(axis=1),:] # 最大与最小值不等的列的index
print(U)

[[1 0 0]
 [1 1 1]
 [1 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [1 1 0]
 [1 1 0]
 [1 0 0]
 [1 0 1]]
[False  True False False False  True False False False False]
[[1 0 0]
 [1 0 1]
 [0 0 1]
 [0 0 1]
 [1 1 0]
 [1 1 0]
 [1 0 0]
 [1 0 1]]
[[1 0 0]
 [1 0 1]
 [0 0 1]
 [0 0 1]
 [1 1 0]
 [1 1 0]
 [1 0 0]
 [1 0 1]]


In [39]:
# 95.将整数向量转换为矩阵二进制表示形式
# I = np.arange(10).astype('int32')
# print(I)
# B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
# print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))# unpackbits函数可以把整数转化成2进制数。
# np.newaxis：增加一个维度

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [56]:
# 96.给定二维数组，如何提取唯一行
Z = np.random.randint(0,2,(6,3))
print(Z)
uZ = np.unique(Z, axis=0)# np.unique函数获取ndarray中的唯一维度的值
print(uZ)

[[0 1 1]
 [0 0 1]
 [0 0 1]
 [1 0 1]
 [0 0 0]
 [1 0 0]]
[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]]


In [57]:
# 97.A和B两个向量，编写相当于内部，外部，总和和mul函数的einsum
# 可以作为einsum的重点习题
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[8.01091028e-04, 3.14319148e-01, 2.71822373e-01, 3.74333587e-01,
        3.71829273e-01, 7.50600508e-02, 3.66233346e-01, 7.21646416e-02,
        3.54594901e-01, 3.46488634e-01],
       [2.01412762e-03, 7.90270837e-01, 6.83424142e-01, 9.41160978e-01,
        9.34864557e-01, 1.88718281e-01, 9.20795104e-01, 1.81438554e-01,
        8.91533370e-01, 8.71152345e-01],
       [1.38901489e-03, 5.44999209e-01, 4.71313883e-01, 6.49058480e-01,
        6.44716242e-01, 1.30146918e-01, 6.35013441e-01, 1.25126556e-01,
        6.14833496e-01, 6.00778008e-01],
       [1.36694872e-03, 5.36341242e-01, 4.63826495e-01, 6.38747406e-01,
        6.34474149e-01, 1.28079378e-01, 6.24925489e-01, 1.23138771e-01,
        6.05066127e-01, 5.91233927e-01],
       [4.77658891e-04, 1.87416075e-01, 1.62076928e-01, 2.23200310e-01,
        2.21707087e-01, 4.47553392e-02, 2.18370457e-01, 4.30289211e-02,
        2.11430913e-01, 2.06597467e-01],
       [1.86175668e-03, 7.30485992e-01, 6.31722364e-01, 8.69961129e-01,
   

In [59]:
# 98.考虑到两个向量（X，Y）描述的路径，如何使用等距样本对其进行采样

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [5]:
# Einsum:爱因斯坦标记法
# 1.简单求和
Z = np.arange(9).reshape(3,3)
print(Z)
print(np.sum(Z,axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 3 12 21]
